### ISSUE TITLE
Horizontal scroll demos not working

### ISSUE THREAD

**Issue by JonQuayle** [baptistebriel/smooth-scrolling#100]
Hi,

I cannot seem to get the horizontal demos to work. All I see is a blank white screen.

Have installed and followed the documentation... any idea what I am doing wrong?

Many thanks,
Jon

**Comment by ammein** [comment]
I agree based on the documentation to open demos is not working because the file is not served on web. You need to serve it either using python or nodejs web server. Or maybe you could use other web server as well.

**Comment by baptistebriel** [comment]
Indeed, you need to have a server running for it to work. I use MAMP on my side but any other similar tool should do the work.
