### ISSUE TITLE
Build version including parallax

### ISSUE THREAD

**Issue by miheins** [baptistebriel/smooth-scrolling#102]
Hi, 
Huge fan, thanks for putting this plugin together! 
Is there any chance you could upload a build version of the plugin using parallax? The build.js versions from the demos are not working for me in my wider project flow but I’d love to get my hands on that parallax.

Thank you!

**Comment by ammein** [comment]
Hi , love to contribute to your project flow using this smooth-scrolling. Mind sharing your code directly to me ? I will have a look closely on your case

**Comment by baptistebriel** [comment]
Hi @miheins –
Have you tried to run the code from the demos locally and re-building the files yourself? Can you describe the exact error/issue you're having with the parallax demo?
Thanks!

**Comment by baptistebriel** [comment]
Maybe this is related to #100?

**Comment by ZachSaucier** [comment]
You could pair this library with GSAP's [ScrollTrigger](http://greensock.com/scrolltrigger) via the [.scrollerProxy() method](https://greensock.com/docs/v3/Plugins/ScrollTrigger/static.scrollerProxy) to create a parallax effect.
