### ISSUE TITLE
Empty space at page bottom when transitioning page

### ISSUE THREAD

**Issue by marioecg** [baptistebriel/smooth-scrolling#104]
Hey Baptiste! Thanks for such awesome library, I love it! 👍 

When first setting up smooth-scrolling I had an issue with empty space at the bottom of the page created by `vs-scroll-view` container, solved it after checking #23 and using the built in css styles. Using barba.js for page transitions results in a similar issue, different heights of empty space are generated in each page.

I remove and add smooth-scrolling before and after leaving each page. Do you know what might be causing the issue?

**Comment by alancoppin** [comment]
Hey @marioecg, Did you find a solution for that ? I have the same problem...

**Comment by marioecg** [comment]
Hey @alancoppin! If I recall correctly resizing smooth after a few ms inside enter/afterEnter view method solved this for me.
