### ISSUE TITLE
Has the latest version been published to NPM?

### ISSUE THREAD

**Issue by jordanmoon** [baptistebriel/smooth-scrolling#107]
It looks like the latest version hasn't been published. I'm still getting back the babel error ` Cannot find module 'babel-preset-es2015'` which was fixed in [this pull request](https://github.com/baptistebriel/smooth-scrolling/pull/105). But I can't see those changes in `node_modules` when installing via NPM.

**Comment by baptistebriel** [comment]
Hey @jordanmoon, you can run `npm install smooth-scrolling@2.3.12` as I just published a new version to npm. Let me know if you still have issues!

**Comment by jordanmoon** [comment]
Hey @baptistebriel works a charm now! Thank you very much for publishing 😄
