### ISSUE TITLE
detect if the instance created extends or direct instance of Smooth

### ISSUE THREAD

**Issue by baptistebriel** [baptistebriel/smooth-scrolling#17]
Currently to extend Smooth in your own file you have to pass an option. I need to know if the instance created extends Smooth or is direct instance of Smooth.

https://github.com/baptistebriel/smooth-scrolling/blob/master/index.js#L17

I've done this so `smooth-scrolling.js` could be used on its own without going into the build process.

**Comment by Awea** [comment]
@baptistebriel something like this `this.extends = this.constructor.name != 'Smooth'` in the constructor ?

**Comment by baptistebriel** [comment]
Awesome, thanks for the hint @Awea ! 👍

**Comment by Awea** [comment]
@baptistebriel np :) Now I wish I can do what I want with this library !

**Comment by baptistebriel** [comment]
Are you having issues with it? Don't hesitate to ask 🙂

**Comment by Awea** [comment]
If I get stuck at some point yeah, thanks !

**Comment by jghlt** [comment]
Hi 
great library thanks!

When I extend the Class, `vars.bounding` is never set.

index.js line 288

```
if(!this.extends) {
  const bounding = this.dom.section.getBoundingClientRect()
  this.vars.bounding = this.vars.direction === 'vertical' ? bounding.height - (this.vars.native ? 0 : this.vars.height) : bounding.right - (this.vars.native ? 0 : this.vars.width)
}
```

Is this desired behaviour?

**Comment by Awea** [comment]
Hi @jghlt,

The `vars.boundings` is correctly set using one of the demo. Can you please provide an example where this is not the case ? :)

**Comment by baptistebriel** [comment]
Hello @jghlt,

Yes indeed, this is an expected behaviour; when you use an extended version of Smooth, you might want to set `this.vars.bounding` manually because it could be something else rather than the `height` of `this.dom.section`. I did this so you could have more control on the scrollable content, while being able to use `smooth-scrolling.min.js` without extending it.

Let me know what you think!

**Comment by jghlt** [comment]
@Awea in the demos it seems to be explicitly set again within the custom.js for each demo.

@baptistebriel Cool, its not a big deal to have to set this again, but might be nice to have an option to retain the default functionality, unless I'm thinking about this in the wrong way?

**Comment by baptistebriel** [comment]
We could check something like this:

```javascript
if(!this.extends || this.options.keepDefaultBounding) {
  const bounding = this.dom.section.getBoundingClientRect()
  this.vars.bounding = this.vars.direction === 'vertical' ? bounding.height - (this.vars.native ? 0 : this.vars.height) : bounding.right - (this.vars.native ? 0 : this.vars.width)
}
```

... but it adds another option, and I thought it would be just simpler to have complete control on the amount of pixels it can scrolls when it's a custom class of smooth-scrolling.

**Comment by jghlt** [comment]
I agree its better to keep options to a minimum, but I think it would be good to have the option to  maintain the default behaviour in this instance, what do you think?
