### ISSUE TITLE
touch devices

### ISSUE THREAD

**Issue by saschalichtenstein** [baptistebriel/smooth-scrolling#2]
hi, 
i tried the smooth scrolling on ipad but it seems that the scrolling is a way too smooth there. what could be the reason?
thanks.

**Comment by baptistebriel** [comment]
Hello,

I'm not sure if I get the issue. Do you mean the scrolling is too slow on touch devices?
Under /lib/vs.js, line 11: try to change the value of the touch multiplier.

`var touchMult = 1;`

Otherwise, could you provide some more infos on the issue? Thanks!

**Comment by saschalichtenstein** [comment]
yeah ok this was the issue. thank you very much
