### ISSUE TITLE
scrollTo() without native scrollbar - Cannot set property 'target' of undefined

### ISSUE THREAD

**Issue by luruke** [baptistebriel/smooth-scrolling#22]
Hello there!

in scrollTo() there is a little typo mistake
https://github.com/baptistebriel/smooth-scrolling/blob/master/index.js#L261

```
this.pos.target = offset
```

Should be

```
this.vars.target = offset
```

Cheers!

**Comment by baptistebriel** [comment]
Indeed, fixed with `smooth-scrolling@2.1.2`
Thank you @luruke !
