### ISSUE TITLE
Empty space at the bottom after resizing

### ISSUE THREAD

**Issue by luruke** [baptistebriel/smooth-scrolling#23]
How to reproduce:
- open https://pierrelevaillant.me/#!/projects with a "desktop" window size. 
- scroll at the bottom.
- make the window smaller.
- notice that the height of the page has changed and now there is "empty space".

![screen shot 2016-04-01 at 16 20 35](https://cloud.githubusercontent.com/assets/61326/14209775/0ca91106-f826-11e5-97e6-89bc1f1c7f72.png)

I temporary fixed forcing the `calc` after resizing.

```
resize() {
    super.resize();

    this.calc({
      deltaX: 0,
      deltaY: 0
    });
}
```

Would be great if it's possible to temporary disable the tweening when applying this fix.

**Comment by baptistebriel** [comment]
Yes, until you scroll again an then it gets recalculated.. Not sure what's the best way to fix that.
We could call this line on `resize` if it uses VirtualScroll;

``` javascript
this.vars.target = Math.max(0, Math.min(this.vars.target, this.vars.bounding))
```

This line is as well used on the [`calcScroll`](https://github.com/baptistebriel/smooth-scrolling/blob/master/index.js#L248) function, when moving the custom scrollbar.

We could do a single function like `clampTarget` that gets called by: `calc`, `calcScroll` and `resize`. I will try to impement this soon as do some testing before releasing it on the next version.

**Comment by lesliecdubs** [comment]
@baptistebriel I'm using the most up-to-date code and I'm still having the same issue as described originally. When the user resizes the browser, there is a gap created at the bottom of the page between the end of the content and the browser bottom. How can this be fixed?

**Comment by baptistebriel** [comment]
Hi @lesliecdub,

Sorry about that! Indeed the test case was wrong and would not call `clampTarget` if using VirtualScroll + has a custom scrollbar. It has been fixed and updating to `smooth-scrolling@2.3.8` should fix the issue.

Let me know!

**Comment by lesliecdubs** [comment]
That did it! Thanks so much @baptistebriel. Great work.

**Comment by baptistebriel** [comment]
You're welcome! 🙂
