### ISSUE TITLE
Not an issue, but how does parallax work?

### ISSUE THREAD

**Issue by jesperlandberg** [baptistebriel/smooth-scrolling#40]
Hi,

Thanks for an excellent plugin. Although this is not an "issue" it would be cool for someone to clarify to me how parallax elements work?

Isn't it just setting a variable, adding a classname and giving the item a data-speed?

http://codepen.io/ReGGae/pen/oLzGaz

**Comment by baptistebriel** [comment]
Hi @jesperlandberg,

Did you tried running the [demos](https://github.com/baptistebriel/smooth-scrolling/tree/master/demos) folder? Parallax is not included in the basic builded file; you need to use an extended one.

Try editing the demo first to get an idea of how this works! Currently the elements are being removed from the DOM when it's not in viewport. You can comment the lines `96` and `105` of [custom.js](https://github.com/baptistebriel/smooth-scrolling/blob/master/demos/parallax/custom.js#L105) so you can debug it more easily.

There must be some ways of including parallax in the default build file, just need some more work. Please let me know what you think!

**Comment by jesperlandberg** [comment]
Hi, thanks for the answer (and sorry for this late bump:P ). Managed to get parallax working how I wanted. 

Rather than starting a new issue thread (as this is not an issue, but not sure were to ask questions=) )... but do you know if it is possible to use scrollmagic (http://scrollmagic.io/) without using native: true?

**Comment by baptistebriel** [comment]
Hi @jesperlandberg,

I don't think that you can use ScrollMagic with VirtualScroll as the plugin's gonna check for the scrollY position of the browser.

What you can do is add a class to the element when it [enters the viewport](https://github.com/baptistebriel/smooth-scrolling/blob/master/demos/split/custom.js#L84) (you can do that with smooth-scrolling only) and then remove the class when it's leaving again -- if you want animations to be run just once, don't remove the class when it leaves the viewport again.

Don't hesitate to ping whenever you have issues or questions!

**Comment by jesperlandberg** [comment]
Thanks, will try it out=)

EDIT: In you example, what is the bare minimum I need to keep to check if in viewport? (trying to "reverse engineer" it myself but any help is appreciated:P

**Comment by baptistebriel** [comment]
Hey @jesperlandberg,

Sorry for the long delay... Not sure if I understand what you mean by 'bare minimum' ?
An element will be out of viewport if;

``` javascript
const inview = bottom > 0 && top < this.vars.height
```
- the `bottom` position is more than 0
- the `top` position of the element is less than the window height

If you want more threshold, you could do something like;

``` javascript
const threshold = 200
const inview = bottom > (threshold * -1) && top < (this.vars.height + threshold)
```

I also just added [another demo](https://github.com/baptistebriel/smooth-scrolling/tree/master/demos/parallax-page) with parallax effects. It's basically the default smooth-scrolling; a transform applied to a .vs-section container but with child elements that will also have transforms applied.

Lemme know :)

**Comment by baptistebriel** [comment]
Feel free to re-open if you have any other questions/issues with parallax scrolling!
