### ISSUE TITLE
How can i extend with custom.js , index.js in demo

### ISSUE THREAD

**Issue by skhtml** [baptistebriel/smooth-scrolling#48]
Hi ! First of all thanks for great plugin, i see the demos and its amazing! 

But i have 2 beginner questions 
1. For example  in demos/opacity/ we have build.js  , index.js , custom.js  in index.html we use only build.js ,  and in build.js  is already extended to work with opacity . But why we need other 2 files ?
Can i just connect smooth-scrolling.js to index.html page , and extend with  custom.js and index.js?

2. It is possible to use smooth scrolling  + parallax ?  yes sure you have demo for parallax but its works alone , without  vs-section container.   i very like to have result like on this demo http://www.eginstill.com/project/loft-val-thorens/    i trying almost 10 hours but not success, thats why i write you :)
I am be very happy if you help me a little

**Comment by baptistebriel** [comment]
Hi @skhtml,

So how things are working in the demos folder;
- `index.js`
- `custom.js`
- `build.js`

`index.js` is the main entry file of the folder where I'll be importing my custom class and just initialising a new instance of the class, right away

``` javascript
import Custom from './custom'

const scroll = new Custom({
  opacity: document.querySelector('h1')
})

scroll.init()
```

`custom.js` will be the extended class of Smooth. In there you can add other elements to transform,  apply opacity to it, etc... Just pass new elements into the options when you initialise the new class (index.js just as above) and get it back into the constructor of your custom class.

``` javascript
import Smooth from '../../index'

class Custom extends Smooth {
  constructor(opt) {
    super(opt)
    this.dom.opacity = opt.opacity
  }
  init() {
    super.init()
    // do something else in init of this class, like adding extra event listeners, etc..
  }
  // etc...
}
```

`build.js` is just the builded file after browserify and babel did their work.

I'll try to take some time to do another demo with the transform of the vs-section + elements inside with different speeds, will get back to you as soon as possible. :)

**Comment by skhtml** [comment]
Ah, now i understand, thank you!  :)   Browserify and babel make build.js from js files. Its like when i use sass and i compile it to css. :) Wow i like it!

About smooth scrolling  vs-section + smooth parallax elements inside of this section. I understand now, when we scroll vs-section with this script, we also need to change in our parallax elements  start trigger viewport , because its depends of vs-section.

Thanks for answer, its will be great if you make it, because i think this script is even better than scrollmagic, ets. because  everything is smooth.

**Comment by baptistebriel** [comment]
Hi @skhtml,

Have a look at the [parallax-page demo](https://github.com/baptistebriel/smooth-scrolling/tree/master/demos/parallax-page), this should be what you need!

Everything works the same as the parallax demo, but you'll find some differences such as the calculations to know if the element is in the viewport (because the parent element .vs-section has a transform applied as well). Elements inside this .vs-section have a position: relative so everything in this section can be a regular website (no fixed positions like the parallax demo).

Let me know what you think!

**Comment by skhtml** [comment]
I just tested it, and it works very good! Thanks , this demo is awesome!  just what i need.  I also test in my test project, and it works perfect as well. :)) 
Thanks man!  

When i come back from my trip, i try add functionality like skrollr . 
`<div class="vs-div" data-end="0.5"  data-change="x:200;y:300;opacity:1">some image</div>`
Its mean from begin of viewport and until  50% (middle) of viewport this div make  transform3d(200,300,0) and opacity:1

**Comment by baptistebriel** [comment]
Glad to know it worked! Feel free to re-open if you have issues!

**Comment by vishalkumar-prajapati** [comment]
build.js is just the builded file after browserify and babel did their work. How did you do that? Please i am new to js things...

**Comment by baptistebriel** [comment]
Hi @vishalp36 — I used `npm scripts` for the build process, see [package.json](https://github.com/baptistebriel/smooth-scrolling/blob/master/package.json#L20). It's basically just using babelify indeed. If your project needs more transforms, you could use tools like gulp or webpack.

**Comment by vishalkumar-prajapati** [comment]
@baptistebriel thanks a (lot)^n
