### ISSUE TITLE
safari trackpad jitter

### ISSUE THREAD

**Issue by maxschulmeister** [baptistebriel/smooth-scrolling#51]
hi,

When on safari using a trackpad i get a very jittery jumpy scroll animation.
I assume this has to do with inertia.

i've set it up like this
```
smooth = new Smooth({
	native: true,
	section: section,
	ease: 0.1,
	vs: {
		limitInertia: true
	}
});
```
should be correct right?
but it does not fix the problem. Am I doing something wrong, or is this a known bug? can anyone replicate this?

**Comment by baptistebriel** [comment]
Hi @max-schu,

First of all, you'll need to pass the `vs` object into options only if you're using `native: false`.
Those are the options for [virtual-scroll](https://github.com/ayamflow/virtual-scroll). It won't be used if the module is using the default browser scrollbar.

I did had the issue with `native: false` and the same `vs` object in parameters (Safari `10.0.1`)
I don't usually use `limitInertia`, I guess you have to look into the [options](https://github.com/ayamflow/virtual-scroll#options) and try on different browsers/devices what's best.

Let me know if you still have the issue when removing the `vs` from options!

**Comment by maxschulmeister** [comment]
ah thanks.

i still doesnt work tho. 

but as it is not happening on your sites, I assume its not a problem with the module. I read about parallax/css translate Problems Safari has with some parallax libraries, so it might be a css related issue. If anyone else experiences this behavior, he might as well want to look into that. 

thank you for your support, keep up the good work 🔥

**Comment by baptistebriel** [comment]
Could you send maybe a screen capture and the version of Safari? Are you experiencing the issues on the `demos` folder of the repo as well?

Let me know ✌️

**Comment by maxschulmeister** [comment]
I've sent you the video on twitter, because it's comissioned work i can't share it here. The bug doesnt occur on your demos. I'm gonna post the solution here if i find out.

thx

**Comment by maxschulmeister** [comment]
turns out the issues in safari was caused by another module called scrollreveal.js which i had used before.
