### ISSUE TITLE
slow scrolling on phone

### ISSUE THREAD

**Issue by philipyoungg** [baptistebriel/smooth-scrolling#63]
Device: iPhone 5s

scrolling is very slow—to the point it feels unresponsive.
tried to change ease to 1. Now the momentum is gone. :(

**Comment by philipyoungg** [comment]
After reading the code, I guess the problem is on `virtual-scroll`.
Space & shift + space scroll also doesn't work. Again, on `virtual-scroll`.

OP, you can close this issue. :)

**Comment by baptistebriel** [comment]
Hey @philipyoungg,
What you're looking for is indeed the `touchMultiplier` option from virtual-scroll.

```javascript
const smooth = new Smooth({
  section: section,
  ease: 0.1
  vs: {
    touchMultiplier: 2
  }
})
```

It defaults is to 1.5 which should be all fine already...
Let me know if that's not what you're looking for.
