### ISSUE TITLE
How can I add class or animation for elements on scroll

### ISSUE THREAD

**Issue by gigholll** [baptistebriel/smooth-scrolling#66]
Hi, your plugin is awesome! 
I am designer, which interested in js , and I have a problem)

In other project I use for this onScreen.js plugin, but it doesn't work. How can I add class or animation for elements on scroll, when they reach viewport?

**Comment by baptistebriel** [comment]
Hi @gigholll! Have you tried running the [demos](https://github.com/baptistebriel/smooth-scrolling/tree/master/demos/parallax) in your browser? There's a few ones where we're adding styles and/or classes to the elements when they reach the viewport.

**Comment by gigholll** [comment]
tnks for fast answer @baptistebriel. I found "key: 'inViewport'" in the code. But i use fix for onScreen.js, that refresh viewport.
var onScreenFix = setInterval(function() {
        $(window).resize();
    }, 500);

**Comment by baptistebriel** [comment]
I wouldn't recommend that fix; all your resize logic might be called when the user is scrolling. This could lead to perfs issues if there's big calculations / dom manipulations done on resize..

**Comment by apollotheme** [comment]
Dear mate,
I wouldn't recommend that fix; all your resize logic might be called when
the user is scrolling. This could lead to perfs issues if there's big
calculations / dom manipulations done on resize..
please tell me more

On Tue, Jul 18, 2017 at 11:49 PM, Apollo Theme <apollotheme@gmail.com>
wrote:

> Dear mate,
>
>
> We are having summer vacation lasts 6 days from 18/7 to 23/7.
> http://www.leotheme.com/blog/609-announce-work-schedule-in-
> summer-vacation-2017.html
> Sorry for inconvenience. We support a little slow, wish you sympathize.
> We will fix it for you as soon as possible.
>
> Best regards
> Support Team
>



-- 
*Best Regards,*

*ApolloTheme Team*

Email: apollotheme@gmail.com
Skype Online Support: trandinhnghiait
Phone Call:(+84) 987 822 810
Website: http://apollotheme.com/
Contact: http://apollotheme.com/ticket/
Facebook: https://www.facebook.com/apollotheme/
