### ISSUE TITLE
Override Smooth

### ISSUE THREAD

**Issue by victor-gabou** [baptistebriel/smooth-scrolling#72]
Hi :)

I am using Smooth for an horizontal scroll, I only would like to override the calc method to change
`const delta = this.vars.direction == 'horizontal' ? e.deltaX : e.deltaY`
with
`const delta = this.vars.direction == 'horizontal' ? e.deltaY : e.deltaX`

So I did
```
import Smooth from 'smooth-scrolling'

class SmoothHorizontal extends Smooth {

    calc(e) {
        const delta = e.deltaY

        this.vars.target += delta * -1
        this.clampTarget()
    }
}

export default SmoothHorizontal
```
but this doesn't work, do you have any idea ?

Thanks :+1:

**Comment by baptistebriel** [comment]
Hey @victor-gabou,

This should indeed work!

Did you make sure you were using `native: false` in the options ?

You could make sure that the code runs through your custom class by adding a `debugger;` or `console.log` statement in your `calc` function.

Let me know!
