### ISSUE TITLE
Smooth Scroll inits fine, but content isn't scrollable.

### ISSUE THREAD

**Issue by 23d1** [baptistebriel/smooth-scrolling#73]
Is there issues running the script together with lazysizes and packery, for example? For some reason, scrolling doesn't work for me, and the helper-div that sets the scroll height based on the `getBoundingClientRect` is at `height: 0;`... 

I've tried initializing before and after load is complete and `preload` both `true` and `false`. So not sure what's happening with the init, as it generates all the classes and so forth. 

It also seems to happen without packery and lazysizes, could it be that I have some elements sized with `vh` and `vw`?

Drawing a blank here, and not very good with JS. :/

Cheers!

**Comment by baptistebriel** [comment]
Hey @23d1,

Using `vh/vw` units shouldn't be an issue.

Does the scrolling works after you resize your browser? I mean wait for the initialization, and just resize your browser after some delay. I would suggest to `console.log` the `getBoundingClientRect` value on resize to see if the value is still at 0 on the second resize.

Also, are you using a specific example from the [demos](https://github.com/baptistebriel/smooth-scrolling/tree/master/demos) folder?

Let me know!

**Comment by 23d1** [comment]
Resizing doesn't solve it. I previously did try moving the init into my document ready loop, which should be somewhat the same (I have a `resize()`; running with a bunch of functions to reapply stuff to an ajax load).

I'm creating the variable with
```
var smooth = new Smooth({
    native: true
});
```
(CSS and .vs-section taken from main.css and native scroll demo)

Then simply running `smooth.init()` in my document ready loop. No scroll.

Is there a way to get around the `position: fixed` on the scrolling element?

**Comment by baptistebriel** [comment]
Could you share the code you're using? The native scroll demo works fine on my side.

**Comment by woowski** [comment]
Hey there !

I'm might having the same issue... The code seems to initialize as is's adding the stuff for the scrollbar and the good class on body. But i'm unable to scroll in what i've define as my vs-section.

Already implement the .js in a classic environnement but i've decided to try that out in Biggie and I definitely running out of idea as i'm pretty new to js. This is the part where i'm trying to add the code.

Hope you could get me on the right track. Cheers mate. Congrats for your fantastic work.

```
constructor(opt) {
    super(opt)
}

init(req, done) {
  super.init(req, done)

  const section = document.querySelector('.vs-section')
  const smooth = new Smooth({
      native: false,
      preload: true,
      section: section,
      ease: 0.1
  })

  smooth.init() 
}

ready(done) {
    super.ready()
    done()
}
```

**Comment by baptistebriel** [comment]
Hi @woowski,

I'll ask the same thing as above to understand better the issue; does the scrolling works after you resize manually your browser?

Also, you could check using Chrome's DevTools and hover the `.vs-section` element and see if it's height is more than the viewport height. Also `console.log(smooth)` should show you all the data; feel free to share a screenshot of the result!

You can also send a link to the biggie repository with the smooth-scrolling code and I can have a look!

**Comment by woowski** [comment]
Damn that was fast ! 

1 / Nope, resizing doesn't have any influence on the result.

2 / Yes, it is higher than the wp.

3 / There you go
<img width="780" alt="capture 2018-02-08 a 20 39 35" src="https://user-images.githubusercontent.com/36222054/35994317-57264f2c-0d10-11e8-8468-e332154eedda.png">

4 / The site is still in its infancy and not online anywhere at the time. I'll upload it to netlify in a couple of hours. 

Please let me know if there's anything i can do helping you solve that issue. The weird thing is that the script work perfectly on a test i did outside biggie env. Thanks a lot ! 

Cheers from france ;)

**Comment by baptistebriel** [comment]
Ah, un Français! 🇫🇷
I'll keep going in English in case other people are having the same issue. 😄

In your resize function, can you `console.log(this.smooth.vars.height)` and see if it's more than `0` ?

I think the reason why it doesn't scroll is because your Smooth function is extending the base `smooth-scrolling`, see `extends: true` in your console.log.

If you extend the base scrolling, you'll have to specify the height value in your own resize function:
https://github.com/baptistebriel/smooth-scrolling/blob/master/index.js#L306

```javascript
import Smooth from 'smooth-scrolling'

class Custom extends Smooth {
  // other methods you want to extend...
  resize() {
    const bounding = this.dom.section.getBoundingClientRect()
    this.vars.bounding = bounding.height - window.innerHeight
    super.resize() // I'm not sure if you need to call the super() before or after the getBoundingClientRect(), I think it's after :)
    console.log(this.vars.height)
    }
}

export default Custom
```

I did that because if you extend the base `smooth-scrolling` I guess you want to have full control on the value to scroll and don't call unnecessary `getBoundingClientRect` on the section.

Let's say if you know you're going to have a scrolling value of `window.innerHeight` or something else, you won't need to read the height of the section.

Tiens-moi au courant!

**Comment by woowski** [comment]
Top merci ! 🇫🇷

Aaaaannnnnddddd i'm lost ...

I'll dig into that and try to figure out what's what. I'll get back to you.

Thanks again. Really appreciate it.

**Comment by baptistebriel** [comment]
No worries — feel free to ask if something is not clear enough 😅

**Comment by woowski** [comment]
Salut ! 

Finally got in working ! How ? I don't know...

Made a new clean install, update most of the npm packages that needed to. Replicate the exact same stuff as i did on my previous test page and it worked right away. So I really don't have a clue of what triggered the problem or what solved it.

Anyway, thanks a lot for your time. Keep up the good work mate. C'est du solide 💪

**Comment by baptistebriel** [comment]
Haha, nickel. Merci mec! 🙌

**Comment by Wakko90** [comment]
Hi guys, I had the same issue and in my case it was caused by a duplicate .vs-section element in my DOM.

Once removed everything worked fine :)

**Comment by 23d1** [comment]
Sorry for the super-long silence! Haha... Still having the same issue. Basically, it's not finding the .vs-section element's height, and so the generated scroll div remains at 0px, with no translation happening to the .vs-section... Only have the one vs-section in DOM and so forth.
