### ISSUE TITLE
Disable Space Bar?

### ISSUE THREAD

**Issue by jonny-harte** [baptistebriel/smooth-scrolling#74]
Hi,

We have smooth-scrolling enable and whenever you press space bar the page scrolls down the height of the viewport. How do you stop this behaviour?

**Comment by baptistebriel** [comment]
Hi @hartey11,

This is not something from `smooth-scrolling` but rather its dependency `virtual-scroll`: https://github.com/ayamflow/virtual-scroll/blob/master/src/index.js#L146

You can always edit this line in your source code if you need to!
