### ISSUE TITLE
Getting rid of native scrollbar

### ISSUE THREAD

**Issue by cupofcrazy** [baptistebriel/smooth-scrolling#75]
Hi Baptiste, I'm trying to figure out how to remove the native scrollbar. Setting the element to `overflow: hidden;` doesn't cut it. Any other options? Thanks.

**Comment by baptistebriel** [comment]
@cupofmint Have you looked at using the option `native: false` ? This will use virtual-scroll instead of native scrolling.

**Comment by cupofcrazy** [comment]
Yeah. When I set it to `native: false` , the smooth scroll stops and the native scrollbar is still visible.

**Comment by baptistebriel** [comment]
Not if you have `overflow: hidden;` on the scrollable element. See [this demo](https://github.com/baptistebriel/smooth-scrolling/tree/master/demos/parallax) for an example!

**Comment by baptistebriel** [comment]
Hi @cupofmint — are you still having the same problem?
Wondering if I can close this issue.
