### ISSUE TITLE
My Footer is cut off (works after resize)

### ISSUE THREAD

**Issue by regenrek** [baptistebriel/smooth-scrolling#77]
Hi,

I have a strange problem on this Site: http://www.ide.co.at/yachting/ When the page initial loads the footer gets cut off. After I resize the page the footer is shown. 
This behaviour shows up with smooth scroll enabled. Any Ideas to solve this?

https://i.imgur.com/wPuPR3s.png

Regards

**Comment by baptistebriel** [comment]
Hi @regenrek, I believe this is due to an image being loaded after the first resize, so the content height to scroll isn't the same anymore. Try passing `preload: true` in the options.

**Comment by regenrek** [comment]
Thank you! This was a great hint.
