### ISSUE TITLE
Scroll with fetch

### ISSUE THREAD

**Issue by sweelemk** [baptistebriel/smooth-scrolling#79]
Hi! 

I want to add elements through the fetch and add class or animation for elements on scroll, when they reach viewport? I can't runing example.

I run, for example: 
`npm run demo-parallax-page`
and i get:
```
> smooth-scrolling@2.3.9 demo-parallax-page E:\web-development\smooth\smooth-scrolling

> watchify -v -t babelify demos/parallax-page/index.js -o demos/parallax-page/build.js

48493 bytes written to demos/parallax-page/build.js (2.52 seconds) at 00:18:29
```

**Comment by baptistebriel** [comment]
Hi @sweelemk,

Sorry for the delay — are you still having this issue? If you use MAMP or something like this, you should be able to access the folder and look at the desired demo.

The build process in the terminal should look like this, so I don't see any issue here. You just need to start a local server to be able to show the demo in your browser.

Hope that helps.
Let me know!
