### ISSUE TITLE
scrollTo with scroll disabled

### ISSUE THREAD

**Issue by mourtazag** [baptistebriel/smooth-scrolling#83]
Hello,

First of all, **THANK YOU** for this librairy, it is so fun to play with it and we can do such beautiful things !

**Here is my problem :** 
- I would like to move my section on mouseY position, i'm using the scrollTo method on throttle mousemove event. It works fine.
- I would like to disable the mousewheel (the usual scrolling behaviour) and only move the section with my mousemove thing.

How can i do that ? When I turn off smooth (smooth.off), the scrollTo method doesn't work anymore.

**An other problem (related but maybe an other issue) :** 
Is it possible to have different behaviour on my mousemove thing and the usual scroll. 
For example, I would like a different ease value for the scrollTo method than the usual scroll.

Thank you again and sorry for the disturbance.
Mourtaza.

**Comment by baptistebriel** [comment]
Hi @mourtazag,

Sorry for the late reply! You could rewrite the index.js file as you need; if you're using the npm module I'd suggest to copy and paste the file in your project directory.

To remove the mousewheel event, you can comment this [line](https://github.com/baptistebriel/smooth-scrolling/blob/master/index.js#L178). Just a heads up, don't forget to comment the related line in the `off` function as well.

For the last question, I guess you could probably add another parameter into the function with an ease value so it's not the same between mousemove and mousewheel events.

Hope it helps!

**Comment by mourtazag** [comment]
Thank you very much for your answer ! I'll try what you suggest !  : )
