### ISSUE TITLE
Custom easing function?

### ISSUE THREAD

**Issue by rijk** [baptistebriel/smooth-scrolling#98]
Hey Baptiste, great package. I am trying to achieve the same effect as on https://louisansa.com/about. Are you using a different easing method there? Can you do this using this package?

**Comment by baptistebriel** [comment]
Hey @rijk –
Indeed, on Louis Ansa's portfolio I just multiply the current value by a factor of .75.
Something like this should do the trick:
```javascript
const value = -(this.vars.current * .75).toFixed(2)
el.style[this.prefix] = this.getTransform(value)
```
Hope it helps!
