### ISSUE TITLE
Horizontal scroll demo with both Y and X scrolling

### ISSUE THREAD

**Issue by tristantbg** [baptistebriel/smooth-scrolling#99]
Is it possible to enable scrolling in the two ways without using native scrolling ?

Thank you for your help!

**Comment by tristantbg** [comment]
I managed to fix this by adding both delta X and Y in the lib :
https://github.com/tristantbg/smooth-scrolling/commit/984cd820f7ac82c4c850b4f266e5439663027c1d

Maybe there is a better way to do it...?

**Comment by baptistebriel** [comment]
You could indeed to this, but I wouldn't recommend doing this. I've had the similar problem on previous projects and we always ended up using either deltaX or deltaY. You could also check which one of the delta is the biggest, and use this one.

**Comment by tristantbg** [comment]
Thanks for the feedback @baptistebriel
